HookedOn/Controllers/CartController.cs
using HookedOn.Interfaces;
using HookedOn.Models;
using HookedOn.Models.AppViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HookedOn.Controllers
{
    public class CartController : Controller
    {
        private readonly IAnimalRepository _animalRepo;
        private readonly ShoppingCart _shoppingCart;

        public CartController(IAnimalRepository animalRepo, ShoppingCart shoppingCart)
        {
            _animalRepo = animalRepo;
            _shoppingCart = shoppingCart;
        }

        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                CurrentCart = _shoppingCart,
                CurrentCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

     
        public RedirectToActionResult AddToShoppingCart(int animalId)
        {
            var selectedAnimal = _animalRepo.GetAnimalById(animalId);
            if (selectedAnimal != null)
            {
                _shoppingCart.AddToCart(selectedAnimal, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int animalId)
        {
            var selectedAnimal = _animalRepo.GetAnimalById(animalId);
            if (selectedAnimal != null)
            {
                _shoppingCart.RemoveFromCart(selectedAnimal);
            }
            return RedirectToAction("Index");
        }
    }
}

HookedOn/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using HookedOn.Interfaces;
using HookedOn.Models;
using Rotativa.NetCore;

namespace HookedOn.Controllers
{
    public class OrderController : Controller
    {
        private readonly IPurchaseRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IPurchaseRepository orderRepository, ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Checkout(Purchase order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your card is empty, buy some pets first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete", new { purchaseId = order.PurchaseId });
            }

            return View(order);
        }

        public IActionResult CheckoutComplete(int purchaseId)
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order! :) ";

            var orderWithDetails = _orderRepository.ShowOrderDetails(purchaseId);

            return View(orderWithDetails);
        }

        /*public IActionResult PDFOrder(int orderId)
        {
            return new ActionAsPdf("CheckoutComplete", new { purchaseId = orderId });
        }*/
    }
}

HookedOn/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HookedOn.Interfaces;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace HookedOn.Controllers
{
    public class StoreController : Controller
    {
        private readonly IAnimalRepository _animalRepo;
        private readonly IModelMetadataProvider _provider;

        public StoreController(IAnimalRepository animalRepo, IModelMetadataProvider provider)
        {
            _animalRepo = animalRepo;
            _provider = provider;
        }

        public IActionResult Index()
        {
            var allAnimals = _animalRepo.GetAllAnimals;

            return View(allAnimals);
        }

        public IActionResult Fish()
        {
            var fishOnly = _animalRepo.GetFish;


            return View(fishOnly);
        }

        public IActionResult Mammals()
        {
            var mammalsOnly = _animalRepo.GetMammals;

            return View(mammalsOnly);
        }

        public IActionResult Reptiles()
        {
            var reptilesOnly = _animalRepo.GetReptiles;

            return View(reptilesOnly);
        }

        public IActionResult IndividualAnimal (string animalName)
        {
            var individualAnimal = _animalRepo.GetAnimalByName(animalName);

            return View(individualAnimal);
        }
    }
}

HookedOn/Views/Cart/Index.cshtml
@model ShoppingCartViewModel

<div class="row checkoutForm">
    <h2>Your shopping cart</h2>
    <h4>Here are the drinks in your shopping cart.</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Selected amount</th>
                <th>Animal</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.CurrentCart.ShoppingCartItems)
            {
                <tr>
                    <td class="text-center">@line.Amount</td>
                    <td class="text-left">@line.Animal.Name</td>
                    <td class="text-right">@line.Animal.Price.ToString("c")</td>
                    <td class="text-right">
                        @((line.Amount * line.Animal.Price).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="Cart" asp-action="RemoveFromShoppingCart" asp-route-animalId="@line.Animal.AnimalId"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.CurrentCartTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Order" asp-action="Checkout" asp-route-order="">Check out</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Add more animals <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Store" asp-action="Fish">Fish</a></li>
                    <li><a asp-controller="Store" asp-action="Mammals">Mammals</a></li>
                    <li><a asp-controller="Store" asp-action="Reptiles">Reptiles</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>